/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$all': RouteRecordInfo<'$all', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'kategoriler': RouteRecordInfo<'kategoriler', '/kategoriler', Record<never, never>, Record<never, never>>,
    'kullanicilar': RouteRecordInfo<'kullanicilar', '/kullanicilar', Record<never, never>, Record<never, never>>,
    'musteriler': RouteRecordInfo<'musteriler', '/musteriler', Record<never, never>, Record<never, never>>,
    'musteriler-id': RouteRecordInfo<'musteriler-id', '/musteriler/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'siparisler': RouteRecordInfo<'siparisler', '/siparisler', Record<never, never>, Record<never, never>>,
    'siparisler-id': RouteRecordInfo<'siparisler-id', '/siparisler/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'slider': RouteRecordInfo<'slider', '/slider', Record<never, never>, Record<never, never>>,
    'urunler-id': RouteRecordInfo<'urunler-id', '/urunler/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
